name: Mirror to Hotel-API-Documentation

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      # 1) Faz checkout sem helper de credenciais
      - name: Checkout full history without credentials helper
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      # 2) Remove a pasta de workflows (apenas na cópia local do runner)
      - name: Remove workflows directory for mirror
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          rm -rf .github/workflows
          # Se houver algo para commitar, cria o commit
          if [ -n "$(git status --porcelain)" ]; then
            git add -A
            git commit -m "Remove workflows for mirror"
          else
            echo "No workflows to remove"
          fi

      # 3) Adiciona o remote do mirror usando o token
      - name: Add mirror remote
        run: |
          git remote add mirror \
            https://x-access-token:${GH_TOKEN}@github.com/Digital-Travel/hotel-api-documentation.git

      # 4) Push só a branch main (já com o commit de remoção) e as tags
      - name: Push main branch and tags to mirror
        run: |
          git push mirror HEAD:main --force
          git push mirror --tags
